# Generated by Django 5.2.6 on 2025-09-26 13:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls_selectionnees', models.TextField()),
                ('statut', models.CharField(choices=[('cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='cours', max_length=10)),
                ('date_lancement', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('progression', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_lancement'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(help_text="ID unique de l'article extrait de l'URL", max_length=50, unique=True, verbose_name="ID de l'article")),
                ('titre', models.TextField(help_text="Titre complet de l'article", verbose_name="Titre de l'article")),
                ('url', models.URLField(help_text="Lien vers l'article original", max_length=500, verbose_name="URL de l'article")),
                ('date_publication', models.CharField(help_text="Date de publication originale de l'article", max_length=100, verbose_name='Date de publication')),
                ('categorie', models.CharField(blank=True, help_text="Catégorie ou rubrique de l'article", max_length=200, null=True, verbose_name='Catégorie')),
                ('date_scraping', models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure du scraping de l'article", verbose_name='Date du scraping')),
                ('nombre_commentaires', models.PositiveIntegerField(default=0, help_text='Nombre total de commentaires pour cet article', verbose_name='Nombre de commentaires')),
                ('nombre_reponses', models.PositiveIntegerField(default=0, help_text='Nombre total de réponses aux commentaires', verbose_name='Nombre de réponses')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_scraping'],
                'indexes': [models.Index(fields=['article_id'], name='Commentaire_article_62f135_idx'), models.Index(fields=['date_scraping'], name='Commentaire_date_sc_20a156_idx'), models.Index(fields=['categorie'], name='Commentaire_categor_4b213a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire_id', models.CharField(help_text='ID unique du commentaire (format: C001, C001R01, etc.)', max_length=100, verbose_name='ID du commentaire')),
                ('auteur', models.CharField(help_text="Nom ou pseudonyme de l'auteur", max_length=200, verbose_name='Auteur du commentaire')),
                ('date_publication', models.CharField(help_text='Date de publication originale du commentaire', max_length=100, verbose_name='Date de publication')),
                ('contenu', models.TextField(help_text='Texte complet du commentaire', validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Contenu du commentaire')),
                ('type', models.CharField(choices=[('commentaire', 'Commentaire principal'), ('reponse', 'Réponse à un commentaire')], max_length=15, verbose_name="Type d'intervention")),
                ('longueur_contenu', models.PositiveIntegerField(help_text='Nombre de caractères dans le commentaire', verbose_name='Longueur du contenu')),
                ('mots_contenu', models.PositiveIntegerField(help_text='Nombre de mots dans le commentaire', verbose_name='Nombre de mots')),
                ('contenu_propre', models.TextField(help_text='Texte du commentaire après nettoyage (HTML, espaces, etc.)', verbose_name='Contenu nettoyé')),
                ('longueur_contenu_propre', models.PositiveIntegerField(help_text='Nombre de caractères dans le contenu nettoyé', verbose_name='Longueur du contenu nettoyé')),
                ('mots_contenu_propre', models.PositiveIntegerField(help_text='Nombre de mots dans le contenu nettoyé', verbose_name='Nombre de mots nettoyé')),
                ('date_extraction', models.DateTimeField(default=django.utils.timezone.now, help_text='Date et heure du scraping du commentaire', verbose_name="Date d'extraction")),
                ('nombre_reponses', models.PositiveIntegerField(default=0, help_text='Nombre de réponses à ce commentaire', verbose_name='Nombre de réponses')),
                ('article', models.ForeignKey(help_text='Article auquel ce commentaire est lié', on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='Commentaires.article', verbose_name='Article associé')),
                ('parent', models.ForeignKey(blank=True, help_text='Commentaire auquel cette réponse est associée', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='Commentaires.commentaire', verbose_name='Commentaire parent')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['article', 'commentaire_id'],
                'indexes': [models.Index(fields=['article', 'type'], name='Commentaire_article_0f12e0_idx'), models.Index(fields=['auteur'], name='Commentaire_auteur_a3aeb1_idx'), models.Index(fields=['date_publication'], name='Commentaire_date_pu_e02bd4_idx'), models.Index(fields=['longueur_contenu'], name='Commentaire_longueu_de96b5_idx')],
                'unique_together': {('article', 'commentaire_id')},
            },
        ),
        migrations.CreateModel(
            name='URLStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('cours', 'En cours de scraping'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='attente', max_length=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Commentaires.article')),
            ],
            options={
                'ordering': ['-date_ajout'],
                'unique_together': {('url',)},
            },
        ),
    ]
