# Generated by Django 5.2.6 on 2025-09-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Commentaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentaire',
            unique_together=set(),
        ),
    ]
